### ISSUE TITLE
Update ASIFT SRS document

### ISSUE THREAD

**Issue by AymenFJA** [iceberg-project/ASIFT#10]
This issue will track the process of updating the SRS-Document for the ASIFT use case.

@AymenFJA  updating the development process of the ASIFT uses based on the SRS requirements.
@mmacferrin is going through the document and will also help to update the document.

**Comment by bspitzbart** [comment]
Need tiling requirements and updated workflow diagram.

**Comment by AymenFJA** [comment]
Need to update the SRS document with all necessary requirements to run 4DGelocation script.

**Comment by AymenFJA** [comment]
Closed for now.
