### ISSUE TITLE
ASIFT Pipeline Stage 2:  RANSAC quality filter to be implemented

### ISSUE THREAD

**Issue by AymenFJA** [iceberg-project/ASIFT#11]
This issue will track the development of the RANSAC QUALITY FILTER (PHASE2) in the ASIFT use case.

@AymenFJA Add the necessary stage and task to the EnTK pipeline and test it.
@mmacferrin Provide task code for the RANSAC quality filter.

**Comment by AymenFJA** [comment]
@mmacferrin I have added the Match two images Milestone to this ticket.

**Comment by mmacferrin** [comment]
RANSAC code is in the "PHASE_3_RANSAC_FILTER" subdirectory, file "ransac_filter.py". It has both a python function and a standalone command-line interface. Let me know if there are issues using it or if it's not documented well enough to use as is.

**Comment by AymenFJA** [comment]
The RANSAC code from phase3 is implemented and working as expected. This ticket will be closed now.
