### ISSUE TITLE
Shared Google_Drive Dataset

### ISSUE THREAD

**Issue by AymenFJA** [iceberg-project/ASIFT#12]
This issue will keep tracking of creating a Google drive folder that will contain the imagery dataset for the ASIFT use case to test the new ASIFT code v2.1.

@AymenFJA will test and profile the ASIFTv2.1 with the provided dataset without the EnTK pipeline on XSEDE BRIDGES.
@mmacferrin will create a shared Google Drive Folder that contains the Imagery dataset.

**Comment by mmacferrin** [comment]
The Google Drive folder is created. I put some images in there to get going. I invited Aymen, Brad and Shantenu (obviously we can invite others as wanted/needed, so long as they're permitted to see/use the imagery).

To note, in any conference presentation, publication, poster, or semi-public display of the data, we need to submit an "Imagery for Public Release" request to the Polar Geospatial Center to comply with the WorldView license. I've attached the document for that form in the Google Drive as well. I will need it for my poster at AGU, for instance.

**Comment by AymenFJA** [comment]
I will start the profile and test process of the ASIFTv2.1 for both the TTX and MEM using the new dataset.

**Comment by mmacferrin** [comment]
Moving the images to the Google Drive Brad set up for the data. I assume you got the same invite I did to that directory.

**Comment by AymenFJA** [comment]
I did, and I will close this Ticket.

Thanks @mmacferrin
