### ISSUE TITLE
ASIFT workflow diagram to be redesigned for Stage 3 and Stage 4 

### ISSUE THREAD

**Issue by AymenFJA** [iceberg-project/ASIFT#14]
**This issue will keep tracking the process of redesigning the workflow diagram of the ASIFT use case .**
   The current workflow diagram does not show specifically what is the input of stage 3 (Geo-Locate) and 
   stage 4 (ortho-rectify) and if there are any data dependencies between each stage.
- [ ] - The workflow diagram of the ASIFT use case will be redesigned (for both Stage 3 and Stage 4) by 
         @mmacferrin.  
- [ ] - @AymenFJA  will redesign the EnTK pipeline(PST model) of (Stage 3 and Stage 4) and reimplelmet 
         the EnTK script for both Stage 3 and Stage 4  based on the new  workflow diagarm.

**Comment by mmacferrin** [comment]
Aymen,

Stage 3 and 4 aren't actually necessary for the first deliverable (trying to get this out the door in a couple months).  I can modify the Workflow diagram as you're outlining here, but we should also make it clear that, as a first deliverable, only Phases 1 and 2 are necessary. Other off-the-shelf software can be used for 3 and 4 and perhaps it is better to stick with 1 and 2 for now.

**Comment by AymenFJA** [comment]
Hey @mmacferrin 

This ticket is actually for the entire ASIFT use case and not only for the first deliverable, but also I created this ticket for the future progress as at some point we will need to implement Stage 3 and Stage 4 as a part of the entire workflow diagram for the use case.

**Comment by AymenFJA** [comment]
Based on the last meeting with @mmacferrin : we added a new stage to the workflow diagram "Image preprocessing" that is responsible for image tiling and contrast enhancement. @mmacferrin I suggest that we update the workflow diagram and the entire document of this use case to match what we currently have in the repository.

**Comment by mmacferrin** [comment]
Yes, I'll update the workflow diagram to reflect these changes and where we
are sitting now. It badly needs it.

**Comment by AymenFJA** [comment]
The workflow diagram is updated  [link is here](https://github.com/iceberg-project/ASIFT/blob/mmacferrin/doc/USE_CASE_DESCRIPTION/ASIFT_Workflew_Diagram_v2_Slide2.JPG).
