### ISSUE TITLE
Command Line Interface 

### ISSUE THREAD

**Issue by AymenFJA** [iceberg-project/ASIFT#15]
Hello @mmacferrin 

For Stage 1 in the workflow diagram, I do understand that we have provide the image inputs and the ``` XOff YOff XSize YSize ```  to every image, but for stage 2  does the user required to provide any input?
if you check to the ICEBERG Asift srs document, you will see in chapter 3 section (3.1) we have to define the Input and output for the user interface. #11

**Comment by mmacferrin** [comment]
For the RANSAC filtering (Stage 2, which is being converted to stage 3), there shouldn't need to be any inputs from the user. There are multiple steps that are involved in running RANSAC on all the tile pairs and then running RANSAC on the re-combined points (from tile-space to whole-image-space) for all the tiles on each image, but none of that should require any specific input from the user, at least in my mind. The RANSAC code should be able to run without input from the user.

I will update the SRS to make this explicit, that's on my ticket list.
