### ISSUE TITLE
Folder restructuring for the ASIFT repository

### ISSUE THREAD

**Issue by AymenFJA** [iceberg-project/ASIFT#17]
I would like to propose the new structre of the ASIFT repository :

```
src -|
 | - EnTK script
 | - ASIFT script
Doc -| 
 |- Use case description
Readme.md

```
please let me know if you have any ideas .

**Comment by bspitzbart** [comment]
For Seals and LandCover we separated the directories by function, or roughly by Stage.
For ASIFT, it might be pre-processing, GCPs, RANSAC, geo-locate, ortho-rectify, for example.

**Comment by mmacferrin** [comment]
This works fine for me... having "src" and "doc" makes sense, with a top-level Readme.md. @bspitzbart's right that the code being sectioned out for each phase (i.e. ASIFT, RANSAC, down the line) makes sense, and is already how I've been doing it.

**Comment by AymenFJA** [comment]
@mmacferrin  so the new structure should look like this :
```
src -|
 | - entk_script
 | - phase1_asift
 | - phase2_ransac
 | - ...
doc -| 
 |- use_case_description
readme.md

```

**Comment by mmacferrin** [comment]
I updated the "mmacferrin" branch to reflect this structure. We can iterate to merge it with your branch (which includes the entk code) soon, so we can be working more in parallel again.

**Comment by AymenFJA** [comment]
Hello @mmacferrin , 
Thanks for the good job that you did in following the desired file structure that we proposed. Unforunailty we still see capitalization in the directories names ` PHASE_1_IMAGE_PREPROCESSING` etc. can you please work on that, please.

**Comment by AymenFJA** [comment]
@mmacferrin  restructured the code as expected, closing this ticket.
