### ISSUE TITLE
Pushed elements

### ISSUE THREAD

**Issue by iparask** [iceberg-project/ASIFT#19]
Hello @AymenFJA @mmacferrin,

There is a number of issues with the repo. First and foremost issue #17 is still open. Can you set a timeline when it will be closed?

Second, I see a lot of  `*.pyc` files. Those are compiled python files and should not be in the repo. You can change the `.gitignore` file by adding all the extension you woul dlike git to ignore and not push.

Third, files names are case sensitive. Not all systems are case-sensitive. Please, change the filenames in lower case. Same goes with folder names.

**Comment by iparask** [comment]
FYI @bspitzbart

**Comment by mmacferrin** [comment]
Yes, I will take care of this. It's a quick switch of the directory
structure, and I will make sure to use all-lower-case filenames rather than
CamelCase. That's on me.

- Mike
