### ISSUE TITLE
Folder ASIFT Scratch

### ISSUE THREAD

**Issue by iparask** [iceberg-project/ASIFT#20]
Why is this folder needed? Does it contain information that is used for testing or validation?

**Comment by iparask** [comment]
FYI @bspitzbart

**Comment by mmacferrin** [comment]
There are a lot of temporary files needed when processing the larger images (tiles, temporary tile-by-tile ASIFT results, etc). Some of them can be generated once and used repeatedly if processing multiple images. They require a structured way for the master program to keep track of them. The "PHASE_1_IMAGE_PREPROCESSING/Scratch_Directory_Manager.py" is used to manage that folder, keep track of temp directories and filenames, etc, while the master program is being executed. The reason the folder exists in the GitHub repo is that it contains a mostly-empty "Scratch_Directory_Log.csv" file used by the manager to keep track of files and temp folders, which it assumes is already in that directory.

When code is executed locally, the Scratch directory can reside anywhere on the local machine or cluster, the location specified in the "File_Locations.py" file in the main directory. I can make these instructions more explicit in the readme.md, which I'll do to resolve this ticket.

(And again, I'll correct the camel-case files and make them all lower-case moving forward, for ticket #19)

**Comment by mmacferrin** [comment]
Got rid of the Scratch directory, updated the README.md with simple instructions for setting it up on a target machine before executing.
