### ISSUE TITLE
README files

### ISSUE THREAD

**Issue by iparask** [iceberg-project/ASIFT#21]
Hello @mmacferrin,

It is very nice to see that you've included README files everywhere. Although I do not see why there are in `md` and `docx` format. Is there a reason for this duplication?

**Comment by iparask** [comment]
FYI @bspitzbart

**Comment by mmacferrin** [comment]
Ioannis,

You're right, they're redundant, which in retrospect isn't helpful. I'll
delete the .docx versions and just maintain the .md versions.

I will also tidy up the formatting, which is a little bit messy in some of
them still, before closing the ticket.

- Mike

**Comment by mmacferrin** [comment]
Ioannis @iparask, you'd noted during our last call today that you would clean up the formatting on the README.md files a bit. Wait just a second before doing that, I am restructuring the folders to be consistent with @AymenFJA's suggestions in Issue #17, which will obviously move the locations of those files. That will be done by end-of-today, I'll tag you when that ticket is closed, and open up a new one if you still wanted to do that.

**Comment by mmacferrin** [comment]
I deleted the "README.docx" files. Just the "README.md" remain.
