### ISSUE TITLE
Fast IMAS IPOL code

### ISSUE THREAD

**Issue by iparask** [iceberg-project/ASIFT#22]
Hello @mmacferrin , @AymenFJA ,

Is there a reason somebody's else code is in our repo? Is the code any different from the one in the mentioned repo?

Assuming the original code is not changed, we can add it to the documentation as a requirement with instructions how to compile it and use it. If it is changed, can someone show me how significant the changes are? We can put the code in a forked repo and use that.

**Comment by iparask** [comment]
FYI @bspitzbart

**Comment by mmacferrin** [comment]
Ioannis,

You're right, it is the same code (un-modified) and a branch from that repo
would be best there. It's is the CPU-implementation that we've been using
and that Aymen is currently using to test different algorithms.

Using a forked repo of "fast_imas_IPOL" would work. Did you want me to add
a fork explicitly within the IceBerg project and link to it, or did you
want to do that? I'm unsure if my permissions on the GitHub allow me to
branch a fork that is managed by IceBerg (and not myself personally).

I will delete the sub-directory and put a more detailed note in the
Readme.md, to fulfill this ticket.

**Comment by mmacferrin** [comment]
(Partially done). I removed the "fast_imas_IPOL" code from the "mmacferrin" branch of the repository.

Not done: Create an IceBerg-specific branch of the "fast_imas_IPOL" repository and document in the IceBerg README.md file user instructions, how to copy/compile that code and where to put it. Assigned to @iparask, per our conversation earlier today. I can update the README.md if you'll create the branch.

**Comment by iparask** [comment]
Yes, please update the `README.md` file and create a Pull request from you branch to devel. When that is merged I will create a forked repo of `fast_imas_IPOL` under ICEBERG git project

**Comment by mmacferrin** [comment]
Yes, I’ll do it in that order (update the README.md, then make a pull request).

- Mike

**Comment by iparask** [comment]
ping @mmacferrin @AymenFJA

**Comment by mmacferrin** [comment]
Pull request #26 initiated.

This pull request, merging the "devel" and "mmacferrin" branches, is beyond the scope of just eliminating the code base for the "fast_imas_IPOL" executable. Once the "fast_imas_IPOL" is branched by @iparask it'd be good to go ahead and close this ticket and use a fresh one to finish the merge, I think, to avoid confusion.

**Comment by AymenFJA** [comment]
`fast_imas_IPOL` code was deleted from ICEBERG/ASIFT repo based on the pull request #26, I will close this issue now.
