### ISSUE TITLE
Performance Metrics for ASIFT success/failure

### ISSUE THREAD

**Issue by mmacferrin** [iceberg-project/ASIFT#24]
Quantifiable metrics, based on:
1) Maximizing number of "good" matching points found, to within "n" pixels
2) Minimizing number of "bad" matches
3) Maximizing spatial coverage of "good" matches across the image. For instance, 10 matching keypoints spaced broadly across an image provides superior geo-rectification than 10 keypoints huddled in one small corner of the image.

From there, we can determine what scores constitute a "success" versus "failed" run of the algorithm. I will add scoring to the "PHASE_3_RANSAC_FILTERING" code.

**Comment by AymenFJA** [comment]
Closed for now.
