### ISSUE TITLE
Image Inventory in Google Drive

### ISSUE THREAD

**Issue by mmacferrin** [iceberg-project/ASIFT#25]
Put ~50 or more images (a selection of both historic airborne, as well as modern Worldview images) in the Google Drive, so @AymenFJA can work more in EnTK implementation.

**Comment by mmacferrin** [comment]
I uploaded a couple of hundred TMA images into the Google Drive "ASIFT/Airborne" directory, will get Worldview images soon. Many are already manually cropped, some are not. I'm writing up an auto-boundary-finder and cropping tool now, which will automate this. (It's part of the necessary workflow specific to the science that was deemed "unnecessary" on a conference call, but is completely necessary regardless).

**Comment by AymenFJA** [comment]
Thank you @mmacferrin I will close this now.
