### ISSUE TITLE
Clone Fast IPOL under ICEBERG

### ISSUE THREAD

**Issue by iparask** [iceberg-project/ASIFT#31]
As agreed fast_IPOL repo is forked under the ICEBERG project. 

We may want to include instructions on how to install it on Bridges since that is the resource we are currently using.

@AymenFJA, can you add here instructions on the installation procedure? That should include module that were loaded, commands executed and a testing example that verifies the installation.

**Comment by AymenFJA** [comment]
@iparask  , In order to run The fas IPOL, there are many instructions need to be written and commands as well, I would suggest that I update the readme file in the 
` phase_2_keypoint_generation `  with a guide on how to make it work and create a pull request referred to this issue.

**Comment by AymenFJA** [comment]
Closed for now.
